import type { ILLMService } from '../types/services.js';

/**
 * Mock LLM Service for development/testing
 * Returns simulated solutions with artificial delay
 */
export class MockLLMService implements ILLMService {
  async generateSolution(prompt: string, model: string): Promise<string> {
    // Simulate varying response times based on model
    const delays: Record<string, number> = {
      'accounts/fireworks/models/llama-v3p1-70b-instruct': 1500,
      'accounts/fireworks/models/qwen2p5-coder-32b-instruct': 1200,
      'accounts/fireworks/models/deepseek-v3': 1800,
    };

    const delay = delays[model] || 1000;
    // Add some randomness (±30%)
    const actualDelay = delay * (0.7 + Math.random() * 0.6);

    await new Promise(resolve => setTimeout(resolve, actualDelay));

    // Extract model name for the mock response
    const modelName = model.split('/').pop() || 'unknown';

    return `// Solution generated by ${modelName}
// Prompt: ${prompt.substring(0, 50)}...

function fixIssue() {
  // Mock implementation
  console.log('Issue fixed by ${modelName}');
  return true;
}

export { fixIssue };
`;
  }
}

/**
 * Real LLM Service using Fireworks AI
 */
export class FireworksLLMService implements ILLMService {
  constructor(private apiKey: string) {
    if (!apiKey) {
      throw new Error('Fireworks API key is required');
    }
  }

  async generateSolution(prompt: string, model: string): Promise<string> {
    const response = await fetch('https://api.fireworks.ai/inference/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: 'system',
            content: 'You are an expert software engineer. Provide clean, working code solutions.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        max_tokens: 2048,
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Fireworks API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json() as {
      choices: Array<{ message: { content: string } }>;
    };

    return data.choices[0]?.message?.content || '';
  }
}
